flowchart LR
    User(["Usuário"])
    Librarian(["Bibliotecário"])

    subgraph LR["Sistema da Biblioteca"]
        App["App do Usuário"]
        Backoffice["App do Bibliotecário"]
        Server["API"]
        DB[("Banco de Dados")]
    end

    Email["Serviço de e-mail"]

    User        -->  |pesquisa e empresta| App
    Librarian   -->  |gerencia livro| Backoffice
    App         -->  |chama API| Server
    Backoffice  -->  |chama API| Server
    Server      -->  |lê e grava| DB
    Server     --->  |monitora e notifica| Email